routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout', 'UserController@logout')->name('logout');
Route::resource('vendor', 'VendorController');
Route::resource('projectmaterial', 'ProjectMaterialController');
Route::resource('projectworker', 'ProjectWorkerController');

Route::get('/project/old/', 'ProjectController@old')->name('project.old');
Route::put('/project/finish/{id}', 'ProjectController@finish')->name('project.finish');
Route::put('/project/close/{id}', 'ProjectController@close')->name('project.close');
Route::put('/project/open/{id}', 'ProjectController@open')->name('project.open');
Route::post('/project/worker/', 'ProjectController@worker');
Route::post('/project/customer/', 'ProjectController@customer');
Route::get('project/pdf/{id}', 'ProjectController@pdf')->name('project.pdf');
Route::resource('project', 'ProjectController');

Route::get('/worker/picture/{id}', 'WorkerController@picture')->name('worker.picture');
Route::post('/worker/picture/{id}', 'WorkerController@setPicture')->name('worker.setpicture');
Route::resource('worker', 'WorkerController');

Route::resource('customer', 'CustomerController');
Route::get('/customer/picture/{id}', 'CustomerController@picture')->name('customer.picture');
Route::post('customer/picture/{id}', 'CustomerController@setPicture')->name('customer.setpicture');

/*Route::group(['prefix' => 'document', 'middleware' => ['auth']], function () {
    Route::get('/', 'Api\DocumentController@list');
    Route::get('/{cod}', 'Api\DocumentController@view');
    Route::post('/{id}', 'Api\DocumentController@store');
    Route::put('/{id}/{cod}', 'Api\DocumentController@update');
    Route::delete('/{id}/{cod}', 'Api\DocumentController@destroy');
});*/

/*Route::group(['prefix' => 'reports'], function() {
	Route::get('/', 'ReportController@index')->name('reports');
  Route::get('/project-resources', 'ReportController@projectResources')->name('reports.resources');
});*/

/*
Route::resource('user', 'UserController');

Route::resource('projectlabors', 'ProjectLaborsController');
Route::resource('projectmerchants', 'ProjectMerchantsController');
Route::resource('projectvendors', 'ProjectVendorsController');
Route::resource('projectbudgets', 'ProjectBudgetsController');
*/

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">

            <!--MIS PROYECTOS-->
            <div class="panel panel-default">
                <div class="panel-heading">My Projects</div>
                <div class="panel-body">
                  @if (count(Auth::user()->project) !== 0)
                      <table class="table table-hover">
                        <thead>
                          <th>Name</th>
                          <th>Description</th>
                          <th>Budget</th>
                        </thead>
                        <tbody>
                          @foreach(Auth::user()->project as $project)
                            <tr>
                              <td>{!! link_to_route('project.edit', $project->name, [$project->id]) !!}</td>
                              <td>{{$project->description}}</td>
                              <td>${!!Form::text('budget', $project->budget, ['class'=>'reader commifyble', 'readonly' => 'true'])!!}</td>
                            </tr>
                          @endforeach
                        </tbody>
                      </table>
                  @else
                        <p>You don't have projects registered</p>

                        <p>Create a new project <a href="/project/create">here</a>.</p>
                  @endif
                </div>
            </div>

            <!--MIS ESTADISTICAS-->
            @if ($projects != 0)
              <div class="panel panel-default">
                  <div class="panel-heading">Statistics</div>
                  <div class="panel-body">
                    <b>Total Budget: </b>${!!Form::text('totalb', $totalb, ['class'=>'reader commifyble', 'readonly' => 'true'])!!}
                    <b>Total Material: </b>${!!Form::text('totalm', $totalm, ['class'=>'reader commifyble', 'readonly' => 'true'])!!} <br>
                    <b>Total Worker: </b>${!!Form::text('totalw', $totalw, ['class'=>'reader commifyble', 'readonly' => 'true'])!!} 
                    <b>Total Invested: </b>${!!Form::text('totali', $totali, ['class'=>'reader commifyble', 'readonly' => 'true'])!!}
                  </div>
              </div>
            @endif
        </div>
        <!--<div id="example">

        </div>-->
    </div>
</div>
@endsection

@section('footer')
<script src="{{ asset('js/commif.js') }}"></script>
@endsection

resources/views/project.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading"><h2>New Project</h2></div>

                <div class="panel-body">
                    <select>
                      <option>Customer 1</option>
                      <option>Customer 2</option>
                      <option>Customer 3</option>
                    </select>
                    <hr>
                    <img class="img-responsive img-circle" src="/company.jpg" style="width:85px; height:85px;">
                    <h4>Customer 1 Company Name</h4>
                    <p>Customer 1 address one</p>
                    <p>Customer 1 address two</p>
                    <p>Customer 1 email</p>
                    <hr>
                    <h3>Project Budget and Description</h3>
                    <div class="row">
                      <div class="col-md-3">
                        <p>Start date</p>
                      </div>
                      <div class="col-md-9">
                        <input type="text" name="budget" value="" placeholder="01/01/2018" class="form-control">
                      </div>
                      <div class="col-md-3">
                        <p>Completation date</p>
                      </div>
                      <div class="col-md-9">
                        <input type="text" name="budget" value="" placeholder="31/12/2018" class="form-control">
                      </div>
                      <div class="col-md-3">
                        <p>Project Budget</p>
                      </div>
                      <div class="col-md-9">
                        <input type="text" name="budget" value="" placeholder="Budget amount" class="form-control">
                      </div>
                      <div class="col-md-3">
                        <p>Project Added Budget</p>
                      </div>
                      <div class="col-md-9">
                        <input type="text" name="budget" value="" placeholder="Budget amount" class="form-control">
                      </div>
                      <div class="col-md-3">
                        <p>Project Description</p>
                      </div>
                      <div class="col-md-9">
                        <textarea name="name" rows="4" cols="71"></textarea>
                      </div>
                    </div>
                    <hr>
                    <h3>Materials</h3>
                      <table class="table table-responsive">
                        <tr class="info">
                          <td>Store</td>
                          <td>Description</td>
                          <td>Attachment</td>
                          <td>Price</td>
                          <td>Count</td>
                          <td>Total</td>
                        </tr>
                        <tr>
                          <td>
                            <select class="form-control">
                              <option>Product</option>
                              <option>Product</option>
                              <option>Product</option>
                            </select>
                          </td>
                          <td>Home Depot Purchase of materials</td>
                          <td><input type="file" name="" value=""></td>
                          <td>69.33</td>
                          <td>1</td>
                          <td>69.33</td>
                        </tr>
                        <tr>
                          <td>
                            <select class="form-control">
                              <option>Product</option>
                              <option>Product</option>
                              <option>Product</option>
                            </select>
                          </td>
                          <td>Lowes Materials</td>
                          <td><input type="file" name="" value=""></td>
                          <td>50.33</td>
                          <td>2</td>
                          <td>100.66</td>
                        </tr>
                      </table>
                      <button type="button" name="button" class="btn btn-default">Add row</button>
                      <hr>
                      <h3>Worker</h3>
                      <table class="table table-responsive">
                        <tr class="success">
                          <td>Worker</td>
                          <td>Name</td>
                          <td>Price hrs</td>
                          <td>Hours</td>
                          <td>Total</td>
                        </tr>
                        <tr>
                          <td>
                            <select class="form-control">
                              <option>Service</option>
                              <option>Service</option>
                              <option>Service</option>
                            </select>
                          </td>
                          <td>Pedro Perez</td>
                          <td>20.00</td>
                          <td>8</td>
                          <td>160.00</td>
                        </tr>
                        <tr>
                          <td>
                            <select class="form-control">
                              <option>Service</option>
                              <option>Service</option>
                              <option>Service</option>
                            </select>
                          </td>
                          <td>Juan Ortega</td>
                          <td>10.00</td>
                          <td>8</td>
                          <td>80.00</td>
                        </tr>
                      </table>
                      <button type="button" name="button" class="btn btn-default">Add row</button>
                    <hr>
                    <button type="button" name="button" class="btn btn-success">Save</button>
                    <div class="" align="right">
                      <h3>Finance</h3>
                      <b>Original Budget: </b>0.00 $<br>
                      <b>Net Profit: </b>0.00 $<br>
                      <b>Net Profit Margin: </b>0.00 %<br>
                      <b>Total: </b>0.00 $<br>
                    </div>
                  </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/reports.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Lista de reportes</div>
                <div class="panel-body">
                  <a href="{{ route('reports.resources') }}" target="_blank">Project Resources</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection