routes/web.php
<?php

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/logout', 'UserController@logout')->name('logout');
Route::resource('vendor', 'VendorController');
Route::resource('projectmaterial', 'ProjectMaterialController');
Route::resource('projectworker', 'ProjectWorkerController');

Route::get('/project/old/', 'ProjectController@old')->name('project.old');
Route::put('/project/finish/{id}', 'ProjectController@finish')->name('project.finish');
Route::put('/project/close/{id}', 'ProjectController@close')->name('project.close');
Route::put('/project/open/{id}', 'ProjectController@open')->name('project.open');
Route::post('/project/worker/', 'ProjectController@worker');
Route::post('/project/customer/', 'ProjectController@customer');
Route::get('project/pdf/{id}', 'ProjectController@pdf')->name('project.pdf');
Route::resource('project', 'ProjectController');

Route::get('/worker/picture/{id}', 'WorkerController@picture')->name('worker.picture');
Route::post('/worker/picture/{id}', 'WorkerController@setPicture')->name('worker.setpicture');
Route::resource('worker', 'WorkerController');

Route::resource('customer', 'CustomerController');
Route::get('/customer/picture/{id}', 'CustomerController@picture')->name('customer.picture');
Route::post('customer/picture/{id}', 'CustomerController@setPicture')->name('customer.setpicture');

/*Route::group(['prefix' => 'document', 'middleware' => ['auth']], function () {
    Route::get('/', 'Api\DocumentController@list');
    Route::get('/{cod}', 'Api\DocumentController@view');
    Route::post('/{id}', 'Api\DocumentController@store');
    Route::put('/{id}/{cod}', 'Api\DocumentController@update');
    Route::delete('/{id}/{cod}', 'Api\DocumentController@destroy');
});*/

/*Route::group(['prefix' => 'reports'], function() {
	Route::get('/', 'ReportController@index')->name('reports');
  Route::get('/project-resources', 'ReportController@projectResources')->name('reports.resources');
});*/

/*
Route::resource('user', 'UserController');

Route::resource('projectlabors', 'ProjectLaborsController');
Route::resource('projectmerchants', 'ProjectMerchantsController');
Route::resource('projectvendors', 'ProjectVendorsController');
Route::resource('projectbudgets', 'ProjectBudgetsController');
*/

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/pmtpro.css') }}" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <a class="navbar-brand" href="{{ route('home') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        @guest
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li>
                                <a href="{{ route('home') }}">Home</a>
                            </li>
                            <li>
                                <a href="{{ route('project.index') }}">Projects</a>
                            </li>
                            <!--<li>
                                <a href="#">Invoices</a>
                            </li>-->
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    Vars <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu">
                                  <li><a href="{{ route('customer.index') }}">Customer</a></li>
                                  <li><a href="{{ route('worker.index') }}">Worker</a></li>
                                  <li><a href="{{ route('vendor.index') }}">Vendors</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
        @include('alerts.success')
        @include('alerts.request')
        @include('alerts.errors')
        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/moment-with-locales.js') }}"></script>
    <script src="{{ asset('js/bootstrap-datetimepicker.min.js') }}"></script>
  	<script src="{{ asset('js/cleave.js') }}"></script>
    <script src="{{ asset('js/pmtpro.js') }}"></script>
    @yield('footer')
</body>
</html>